const ShopActionTypes = {
  FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
  FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
  FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE',
    REQUEST_API_ITEMS_PENDING: '  REQUEST_API_ITEMS_PENDING',
  REQUEST_API_ITEMS_SUCCESS: '  REQUEST_API_ITEMS_SUCCESS',
  REQUEST_API_ITEMS_FAILED: '  REQUEST_API_ITEMS_FAILED'
};

export default ShopActionTypes;
